# Generated by Django 3.1.7 on 2021-03-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
