# Generated by Django 3.1.7 on 2021-03-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_tweet_tweet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='text',
        ),
    ]
